name: Sync to Public Repo

on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"
          git remote add upstream https://github.com/Zespul/zespul-public.git
      - name: Fetch from upstream
        run: git fetch upstream
      - name: Merge upstream/master into master
        run: git merge upstream/master
      - name: Push to upstream
        run: git push upstream master
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_PAT }}